### ISSUE TITLE
The activities view isn't hidden when I select a activity

### ISSUE THREAD

**Issue by i5o** [SAMdroid-apps/aslo#2]
Try to select an activity, then scroll down, you will see the 'featured' and 'all-activities' is still here.

**Comment by samdroid-apps** [comment]
Now I get what your saying!

This is actually the deaired outcome.  Is this confusing?

**Comment by i5o** [comment]
Yes it is, because you added the back button http://i.imgur.com/9klQJml.png

**Comment by samdroid-apps** [comment]
Does this fix it?

![](http://i.gyazo.com/0677738fc570383764fbaf446d8da38f.png)

**Comment by samdroid-apps** [comment]
Discussion from IRC:

```
15:19     samdroid | ignacio: https://github.com/SAMdroid-apps/aslo/issues/2#issuecomment-71587559
15:20      ignacio | samdroid: I think you need to hide the bibliography thing too
15:20     samdroid | ignacio: And the activity list?
15:20      ignacio | samdroid: yeah
15:21     samdroid | ignacio: I like how the use can scroll down and view the activities
15:21     samdroid | ignacio: But I will give it a go
15:21     samdroid | ignacio: 'cause I'm probably wrong :)
15:21      ignacio | samdroid: well, the point is: I like to see the current activity, no others
```

**Comment by samdroid-apps** [comment]
Ok, here is my fix:

![Gyazo](http://i.gyazo.com/3305b0cd23d037e9c975b7e354e70dd5.png)](http://gyazo.com/3305b0cd23d037e9c975b7e354e70dd5)
